export const GET_ALL_BEERS_PENDING = 'GET_ALL_BEERS_PENDING'
export const GET_ALL_BEERS_SUCCESS = 'GET_ALL_BEERS_SUCCESS'
export const GET_ALL_BEERS_FAILED = 'GET_ALL_BEERS_FAILED'

export const GET_RANDOM_BEER_PENDING = 'GET_RANDOM_BEER_PENDING'
export const GET_RANDOM_BEER_SUCCESS = 'GET_RANDOM_BEER_SUCCESS'
export const GET_RANDOM_BEER_FAILED = 'GET_RANDOM_BEER_FAILED'


